"""Initial schema with locations, panchang_cache, term_definitions

Revision ID: bc2fe3d73e21
Revises: 
Create Date: 2026-02-06 21:31:28.768059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2fe3d73e21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('is_preloaded', sa.Boolean(), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'state', 'country', name='uq_location_identity')
    )
    op.create_index('ix_locations_coordinates', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_locations_country'), 'locations', ['country'], unique=False)
    op.create_index(op.f('ix_locations_latitude'), 'locations', ['latitude'], unique=False)
    op.create_index(op.f('ix_locations_longitude'), 'locations', ['longitude'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_index('ix_locations_name_country', 'locations', ['name', 'country'], unique=False)
    op.create_table('panchang_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('panchang_data', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'date', name='uq_panchang_cache_entry')
    )
    op.create_index(op.f('ix_panchang_cache_date'), 'panchang_cache', ['date'], unique=False)
    op.create_index(op.f('ix_panchang_cache_expires_at'), 'panchang_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_panchang_cache_location_id'), 'panchang_cache', ['location_id'], unique=False)
    op.create_index('ix_panchang_cache_lookup', 'panchang_cache', ['location_id', 'date'], unique=False)
    op.create_table('term_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('short_definition_en', sa.Text(), nullable=False),
    sa.Column('detailed_explanation_en', sa.Text(), nullable=False),
    sa.Column('name_ta', sa.String(length=255), nullable=False),
    sa.Column('short_definition_ta', sa.Text(), nullable=False),
    sa.Column('detailed_explanation_ta', sa.Text(), nullable=False),
    sa.Column('significance_tradition', sa.Text(), nullable=True),
    sa.Column('calculation_method', sa.Text(), nullable=True),
    sa.Column('related_terms', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_term_definitions_term_id'), 'term_definitions', ['term_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_term_definitions_term_id'), table_name='term_definitions')
    op.drop_table('term_definitions')
    op.drop_index('ix_panchang_cache_lookup', table_name='panchang_cache')
    op.drop_index(op.f('ix_panchang_cache_location_id'), table_name='panchang_cache')
    op.drop_index(op.f('ix_panchang_cache_expires_at'), table_name='panchang_cache')
    op.drop_index(op.f('ix_panchang_cache_date'), table_name='panchang_cache')
    op.drop_table('panchang_cache')
    op.drop_index('ix_locations_name_country', table_name='locations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_longitude'), table_name='locations')
    op.drop_index(op.f('ix_locations_latitude'), table_name='locations')
    op.drop_index(op.f('ix_locations_country'), table_name='locations')
    op.drop_index('ix_locations_coordinates', table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
